<?php
return [    
    //
    "l_tbridge"=>"T-BRIDGE",
    // login
    "l_id" => "ID",
    "l_password" => "Mật khẩu",
    "l_saveid" => "Lưu ID",
    "l_savedraft" => "Lưu Tạm",
    "l_login" => "Đăng nhập",
    "l_signup" => "Đăng ký",
    "l_findid" => "Tìm ID",
    "l_findpw" => "Tìm mật khẩu",
    "l_titlelogin" => "Giải pháp tổng cho người bán vé / du lịch",
    // warning
    "l_inputisset"=>"Giá trị không tồn tại!",
    "l_inputempty"=>"Vui lòng nhập đầy đủ thông tin!",
    "l_inputid" => "Hãy nhập vào ID",
    "l_inputiderr" => "ID không hợp lệ",
    "l_inputpw" => "Hãy nhập vào mật khẩu",
    "l_notidpw" => "ID hay mật khẩu không đúng",
    "l_accountunactive" => "Tài khoản của bạn chưa được kích hoạt.",
    
    // find ID
    "l_codetax" => "Mã ĐK Doanh nghiệp",
    "l_email" => "Email",
    "l_codeconfirm" => "Mã xác nhận",
    "l_sendcodeconfirm" => "Gởi Code",
    "l_titlefindid" => "Tìm ID T-Bridge giải pháp tổng hợp bán vé/du lịch",
    // warning
    "l_inputcodetax" => "Hãy nhập vào Mã ĐK Doanh nghiệp",
    "l_errorcodetax" => "Mã ĐK Doanh nghiệp không hợp lệ",
    "l_inputemail" => "Hãy nhập vào email",
    "l_erremail" => "Email không hợp lệ",
    "l_notemail" => "Email không đúng.",
    "l_inputcodeconfirm" => "Điền vào mã xác nhận",
    "l_errcodeconfirm" => "Mã xác thực không chính xác.",
    "l_errcodetaxemail" => "Mã ĐK Doanh nghiệp và Email không đúng",
    "l_yourid" => "ID của quý khách là : ",
    "l_yourid1" => "",
    "l_confirmemail" => "Mã xác thực đã được gửi đến email.<br>Nếu không thấy trong Inbox, vui lòng kiểm tra hộp thư Spam.",
    "l_confirmemail1" => "Mã xác thực đã được gửi đến email.\\nNếu không thấy trong Inbox, vui lòng kiểm tra hộp thư Spam.",
    // find PW
    "l_titlefindpw" => "Tìm PW T-Bridge giải pháp tổng hợp bán vé/du lịch",
    // warning
    "l_errIDemail" => "ID và Email không đúng",
    "l_errID" => "ID không đúng",
    "l_confirmPW" => "Mật khẩu tạm đã được gửi đến email.\\nVui lòng kiểm tra tại email mà bạn đã cung cấp.\\nNếu không thấy trong Inbox, vui lòng kiểm tra hộp thư Spam.",
    
    // signup
    "l_titlesignup" => "T-BRIDGE Đăng ký thành viên miễn phí",
    "l_titleusetbridge" => "Thông tin sử dụng T-Bridge",
    "l_titlepersonresponsible" => "Thông tin người phụ trách",
    "l_titlepersonresname" => "Tên người phụ trách",
    "l_titlepersonresnameadd" => "Thêm người phụ trách",
    "l_titlecompany" => "Thông tin doanh nghiệp",
    "l_master" => "Master",
    "l_seller" => "Người bán",
    "l_supplier" => "Nhà cung cấp",
    "l_supplierinfo" => "Thông tin nhà cung cấp",
    "l_supplieradd"=>"Thêm nhà cung cấp",
    "l_supplierall"=>"Thêm nhiều NCC",
    "l_companyconfirm" => "Xác thực DN",
    "l_warnid" => "Tổ hợp từ 4 ký tự trở lên bao gồm chữ, số",
    "l_warnpassword" => "Từ 6 đến 20 ký tự, nên có đủ ký tự số/chữ/ký tự đặc biệt",
    "l_confirmpassword" => "Xác nhận mật khẩu",
    "l_person_responsible" => "Người chịu trách nhiệm",
    "l_phone" => "Điện thoại",
    "l_confirmcodeconfirm" => "Xác nhận",
    "l_company" => "Công ty",
    "l_person_surrogate" => "Người đại diện",
    "l_career" => "Ngành nghề",
    "l_status" => "Trạng thái",
    "l_taxcode" => "Mã số thuế",
    "l_textarea1" => "Đồng ý với điều khoản sử dụng của T-Bridge.",
    "l_textarea2" => "Đồng ý cho T-Bridge thu thập và sử dụng thông tin cá nhân.",
    "l_tax1" => "3 ký tự số",
    "l_tax2" => "2 ký tự số",
    "l_tax3" => "5 ký tự số",
    "l_changeemail" => "Đổi email",
    "l_accountbank" => "Tài khoản Ngân hàng",
    "l_accountimagebank" => "Bản sao sổ tài khoản",
    "l_dkkdname" => "Giấy ĐKKD",
    "l_dkkdupload" => "Upload Giấy ĐKKD",
    "l_accountbankupload" => "Upload STK",
    "l_erraccountbankupload" => "Vui lòng Upload bản sao sổ tài khoản",
    "l_rule" => "Đồng ý điều khoản",
    "l_rule01" => "Điều khoản sử dụng",
    "l_rule02" => "Chính sách sử dụng thông tin cá nhân",
    "l_rulefile01" => "Chấp nhận tập tin có định dạng (.pdf)",
    "l_errruledkkd" => "Vui lòng kiểm tra mã đăng ký doanh nghiệp.",
    "l_errrule" => "Vui lòng đồng ý với điều khoản.",
    "l_errrfiledkkd" => "Vui lòng tải giấy đăng ký kinh doanh.",
    "l_errExtension"=>"Định dạng tập tin không hợp lệ! Định dạng hợp lệ là",
    "l_errSize"=>"Kích thước tập tin không phù hợp! Kích thước tối đa là ",
    "l_errFolder"=>"Thư mục không hợp lệ!",
    
    // warning
    "l_exittax" => "Mã ĐK doanh nghiệp đã tồn tại ~~",
    "l_inputtax"=>"Vui lòng nhập mã mã xác thực",
    "l_exitemail" => "Email đã tồn tại ~~",
    "l_warnid1" => "ID không được chứa ký tự đặc biệt",
    "l_warnid2" => "ID đã tồn tại",
    "l_warnpw1" => "Mật khẩu chứa ký tự, số và ký tự đặc biệt",
    "l_warnpw2" => "Mật khẩu không hợp lệ mật khẩu hợp lệ từ 6-20 ký tự",
    "l_warnpw3" => "Xác nhận mật khẩu ko trùng",
    "l_warnpw4" => "Lỗi! không thể thay đổi mật khẩu vui lòng thử lại sau",
    "l_warnemail2" => "Lưu ý : Hóa đơn thuế được gửi đến email cung cấp.",
    "l_inputperson_responsible" => "Điền vào Người phu trách",
    "l_inputphone" => "Điền vào số điện thoại",
    "l_warnemail1" => "Email chưa được xác thực",
    "l_inputcompany" => "Điền vào Tên công ty",
    "l_inputperson_surrogate" => "Điền vào Người đại diện",
    "l_inputcareer" => "Điền vào Nganh nghề",
    "l_inputabank" => "Tên chủ tài khoản",
    "l_inputabankconfirm" => "Xác thực tài khoản",
    "l_changeabank" => "Thay đổi tài khoản",
    "l_abankname" => "Vui lòng chọn Tài khoản Ngân hàng",
    "l_inputabanknumber" => "Nhập số tài khoản không có dấu ‘-’",
    "l_inputstatus" => "Điền vào Trạng Thái",
    "l_inputtaxcode" => "Điền vào Mã số Thuế",
    "l_agree1" => "Bạn chưa đồng ý với điều khoản sử dụng.",
    "l_agree2" => "Bạn chưa đồng ý với chính sách quyền riêng tư",
    "l_warnsignup1" => "Đăng ký không thành công",
    "l_warnsignup2" => "Đã đăng ký thành công",

    // logout
    "l_welcome" => "Xin chào",
    "l_logout" => "Đăng xuất",
    "l_areyousure" => "Bạn có chắc không???",
    "l_support" => "Hướng dẫn sử dụng",
    "l_accountinfo" => "Thông tin tài khoản",
    
    // account
    "l_changepassword" => "Thay đổi mật khẩu",
    "l_newpassword" => "Mật khẩu mới",
    "l_confirmnewpassword" => "Nhập lại mật khẩu",
    "l_sendpasswordtmp"=>"Gửi mật khẩu tạm",
    "l_warnpw5" => "Lưu mật khẩu mới thành công",
    "l_warnrperson" => "Lưu thông tin người phụ trách thành công",
    "l_warnrpersonfailed" => "Lưu thông tin người phụ trách thất bại",
    "l_warnrpersonerror" => "Lỗi! không thể xóa người phụ trách",
    "l_warnsperson" => "Lưu thông tin Doanh nghiệp thành công",
    "l_manageinfo"=>"Quản lý thông tin",
    "l_manageinfodescription"=>"Có thể sửa và quản lý các thông tin như mật khẩu/số tài khoản/số điện thoại.",
    "l_accaddress"=>"Địa chỉ",
    "l_accaddressfind"=>"Tìm địa chỉ",
    "l_acccode"=>"Mã lô",
    "l_acczipcode"=>"Mã bưu chính",
    "l_accrole"=>"Quyền hạng",
    "l_accupdateinfo"=>"Cập nhật thông tin",
    "l_accpersondescription"=>'Nếu có nhiều người phụ trách, vui lòng bấm vào nút "Thêm thông tin người phụ trách" để thêm.',
    "l_worktimeout"=>"Thời gian làm việc",
    "l_example"=>"VD) ",
    "l_workinweek"=>"Trong tuần",
    "l_worksaturday"=>"Thứ Bảy",
    "l_workdayoff"=>"Ngày nghỉ",
    "l_worktimeoff"=>"Nghỉ Chủ Nhật, Ngày Lễ",
    "l_phonenumeric"=>"Số điện thoại",
    "l_landlinenumber"=>"Số điện thoại cố định *",
    "l_landlinenumberservice"=>"Số điện thoại tư vấn *",
    "l_landlinenumber1"=>"Giống với số bàn *",
    "l_landlinenumber2"=>"Số điện thoại hủy *",
    "l_landlinenumber3"=>"Hotline *",
    "l_parking"=>"Chỗ đậu xe",
    "l_parking1"=>"Không đậu xe",
    "l_parking2"=>"Có đậu xe",
    "l_parking3"=>"Phí gởi xe",
    "l_website"=>"Website",
    "l_emailandfax"=>"Email/Fax",
    "l_accmanage"=>"Quản lý",
    "l_acctable1"=>"Tên NCC",
    "l_acctable2"=>"Sử dụng",
    "l_acctable12"=>"Không sử dụng",
    "l_acctable3"=>"Người PT",
    "l_acctable4"=>"Số dt PT",
    "l_acctable5"=>"Đại diện PL",
    "l_acctable6"=>"Mã DKDN",
    "l_acctable7"=>"Ngành nghề",
    "l_acctable8"=>"Ngân hàng",
    "l_acctable9"=>"Số tài khoản", 
    "l_acctable10"=>"Tên người bán", 
    "l_acctable11"=>"Thêm NCC",
    
    // Member
    "l_mbtotal"=>"Tổng ",
    "l_mbconfirm"=>"Xử lý duyệt",
    "l_companyname"=>"Tên công ty",
    "l_postlive"=>"Đăng trực tiếp",
    
    // Notification
    "l_notification1"=>"Vui lòng nhập vào tiêu đề",
    "l_notification2"=>"Vui lòng nhập vào nội dung",
    "l_notification3"=>"Lỗi! không thể thêm nội dung thông báo.",
    "l_notification4"=>"Lỗi! không thể chỉnh sửa thông báo",
    "l_notification5"=>"Vui lòng nhập vào từ khóa tìm kiếm",
    "l_notification6"=>"Thông báo",
    "l_notification7"=>"Thông báo chung cho dịch vụ của T-Bridge.",
    "l_notification8"=>"Kết quả",
    "l_notification9"=>"Đăng mới",
    "l_notification10"=>"Tiêu đề",
    "l_notification11"=>"Người đăng lần đầu",
    "l_notification12"=>"Ngày đăng lần đầu",
    "l_notification13"=>"Người đăng lần cuối",
    "l_notification14"=>"Ngày đăng lần cuối",
    "l_notification15"=>"공지사항 등록",
    "l_notification16"=>"",
	"l_notification17"=>"최종수정자",
	"l_notification18"=>"최종수정일시",
	"l_notification19"=>"공지사항 수정",
    
    // Channel
    "l_Channel1"=>"Vui lòng upload tập tin .xlsx",
    "l_Channel2"=>"Vui lòng nhập tên kênh",
    "l_Channel3"=>"Vui lòng nhập ID kênh",
    "l_Channel4"=>"Không thể thêm phân loại kênh bán",
    "l_Channel5"=>"Phân loại kênh bán",
    "l_Channel6"=>"Có thể quản lý phân loại hiển thị trên từng kênh bán. (Chỉ có thể upload excel)",
    "l_Channel7"=>"Tên kênh",
    "l_Channel8"=>"ID kênh",
    "l_Channel9"=>"Số phân loại",
    "l_Channel10"=>"Không thể thêm phân cấp cho phân loại này",
    "l_Channel11"=>"Vui lòng chọn mục phân loại cần thêm",
    "l_Channel12"=>"Không thể thêm phân cấp cho phân loại này",
    "l_Channel13"=>"Vui lòng nhập vào tên phân loại",
    "l_Channel14"=>"Vui lòng chọn trạng thái phân loại",
    "l_Channel15"=>"Thêm phân loại mới thất bại",
    "l_Channel16"=>"Vui lòng chọn phân loại cần sửa",
    "l_Channel17"=>"Vui lòng nhập vào tên phân loại",
    "l_Channel18"=>"Vui lòng chọn trạng thái phân loại",
    "l_Channel19"=>"Vui lòng chọn phân loại cần xóa",
    "l_Channel20"=>"Lưu ý: nếu xóa phân loại này thì tất cả phân loại bên trong cũng bị xóa!",
    "l_Channel21"=>"Không thể xóa phân loại vui lòng kiểm tra lại",
    "l_Channel22"=>"Phân loại T-Bridge",
    "l_Channel23"=>"Tạo/xóa phân loại trên T-Bridge và quản lý so khớp với phân loại hiển thị trên kênh bán.",
    "l_Channel24"=>"Xuống",
    "l_Channel25"=>"Lên",
    "l_Channel26"=>"Download Excel",
    "l_Channel27"=>"Thêm phân loại",
    "l_Channel28"=>"Xóa phân loại",
    "l_Channel29"=>"Chỉ xem phân loại sử dụng",
    "l_Channel30"=>"Phân cấp",
    "l_Channel31"=>"Tên phân loại",
    "l_Channel32"=>"Trạng thái phân loại",
    "l_Channel33"=>"So khớp phân loại với kênh bán",
    "l_Channel34"=>"Đăng",
    "l_Channel35"=>"Hủy",
	"l_ok"=>"Ok",
    "l_Channel36"=>"Upload Excel",
    "l_Channel37"=>"Download mẫu",
    "l_Channel38"=>"Vui lòng nhập tiêu đề",
    "l_Channel39"=>"Vui lòng nhập nội dung thông báo",
    "l_Channel40"=>"Phân loại T-Bridge",
    "l_Channel41"=>"Phân loại kênh bán",
    "l_Channel42"=>"Quản lý so khớp",
    "l_Channel43"=>"Cập nhật",
    "l_Channel44"=>"Thêm mới",
    
    // menuleft
    "l_dashboard" => "Dashboard",
    "l_addproduct" => "Đăng sản phẩm",
    "l_ticket" => "Vé",
    "l_rentcar" => "Thuê xe",
    "l_manageproduct" => "Quản lý sản phẩm",
    "l_manageorder" => "Quản lý đơn hàng",
    "l_managerevenue" => "Quản lý doanh thu",
    "l_managequestion" => "Quản lý hỏi đáp",
    "l_managetype" => "Quản lý phân loại",
    "l_managemember" => "Quản lý thành viên/quyền hạn",
    "l_manageprole" => "Quản lý quyền hạn",
    "l_notification" => "Thông báo",
    "l_managemember1"=>"Có thể xem danh sách thành viên đăng ký, xử lý duyệt và quản lý quyền hạn",
    "l_managerevenue1" => "Chi tiết doanh thu",
    "l_managerevenue2" => "Quyết toán kênh bán",
    "l_managerevenue3" => "Tình hình quyết toán ",
    
    // top
    "l_top01" => "Xác thực doanh nghiệp",
    "l_top02" => "Nhập thông tin",
    "l_top03" => "Vui lòng xác thực mã đăng ký doanh nghiệp.",
    "l_top04" => "Nhập thông tin để sử dụng dịch vụ.",
    "l_top1" => "1. 상품정보",
    "l_top2" => "2. 옵션정보",
    "l_top3" => "3. 구매/환불조건",
    "l_top4" => "4. 이미지",
    "l_top5" => "5. 이용정보",
    "l_top6" => "3 Landmarks/Location/Reservation",
   
    // addticket1
    "l_infoproduct" => "Thông tin sản phẩm",
    "l_codeproduct" => "Mã sản phẩm",
    "l_typeproduct" => "Loại sản phẩm",
    "l_type" => "Phân loại",
    "l_type1" => "Phân loại cấp 1",
    "l_type2" => "Phân loại cấp 2",
    "l_type3" => "Phân loại cấp 3",
    "l_type4" => "Phân loại cấp 4",
    "l_nameproduct" => "Tên sản phẩm",
    "l_adultOnly" => "adultOnly",
    "l_tagsproduct" => "Gắn thẻ sản phẩm",
    "l_warntagsproduct" => "Nhập tối đa 10 thẻ, cách nhau bần dấu (,)",
    "l_displayKeyword" => "display Keyword",
    "l_warndisplayKeyword" => "Local keywords to display on your product (each keyword maximum string length is 10 characters)",
    "l_displayCategoryCode" => "display Category Code",
    "l_warndisplayCategoryCode" => "Impression category of the product. Example: 106774 (This item cannot be changed after creation)",
    "l_pricerepresentative" => "Giá đại điện",
    "l_pricebasic" => "Căn cứ giá chuẩn",
    "l_typesale" => "Loại hình bán",
    "l_typesale1" => "Sản phẩm voucher",
    "l_typesale2" => "Sản phẩm qui định ngày",
    "l_listoption" => "Danh sách Option",
    "l_regional_category" => "Regional Category",
    "l_warnproduct" => "Điền vào tên sản phẩm",
    "l_warntagsproduct1" => "Nhập ít nhất 1 Searchtags",
    "l_warnproduct1" => "Thêm danh sách option",
    "l_warnproduct2" => "Hãy chọn option đại diện",
    "l_warnimage1" => "Hãy chọn hình đại diện",
    "l_warnimage2" => "Hãy chọn hình ngang đại diện",
    "l_warnimage30"=>"Mỗi tag sản phẩm chỉ đc nhập tối đa 10 ký tự",
    
    // option
    "l_travelItemId" => "Mã option",
    "l_onsale" => "On Sale",
    "l_nameoption" => "Tên option",
    "l_taxType" => "tax Type",
    "l_description" => "Description",
    "l_period" => "Hiệu lực",
    "l_rates" => "Rates",
    "l_warnname" => "ký tự",
    
    //
    "l_imageproduct" => "Hình sản phẩm",
    "l_image1" => "Hình đại diện",
    "l_image2" => "Recommended size: 460X460 / Up to 10 can be registered",
    "l_image3" => "Kích thước đề xuất: 790 ngang (không giới hạn dọc), có thể đăng ký tối đa 50 tờ",
    "l_image4" => "Kích thước đề xuất: 790 ngang (không giới hạn dọc), có thể đăng ký tối đa 50 tờ",
    "l_contentdetail" => "Nội dung chi tiết",
    "l_content" => "Nội dung",
    "l_warnimage" => "Upload 1 hình đại diện",
    "l_warnimage3" => "Upload tối đa 10 hình đại diện",
    "l_warnimage4" => "Upload tối đa 10 hình ngang",
    "l_warnimage5" => "Upload 1 hình ngang",
    "l_warncontent" => "Upload 1 hình content",
    
    //
    "l_traffic" => "Traffic",
    "l_trafficinfo" => "Traffic info",
    "l_publicTransportInfo" => "publicTransportInfo",
    "l_landmarks" => "Landmarks",
    "l_nearbyLandmarks" => "nearbyLandmarks",
    "l_locations" => "locations",
    "l_reservation" => "reservation",
    "l_booking" => "Booking",
    "l_reservationGuide" => "reservationGuide",
    "l_reservationNotifications" => "reservationNotifications",
    "l_warnexternalCouponUseType" => "Nhập vào externalCouponUseType",
    "l_warnphonetable"=>"Điền vào điện thoại bàn",
    "l_warnphoneadvisory"=>"Điền vào điện thoại tư vấn",
    "l_warnphonecancel"=>"Điền vào điện thoại hủy",
    "l_warnhotline"=>"Điền vào điện thoại hotline",
    "l_warnwebsite"=>"Điền vào website",
    "l_warnemail"=>"Điền vào Email",
    "l_warnfax"=>"Điền vào số fax",
    
    //
    "l_conditionsell" => "Điều kiện bán",
    "l_timesell" => "Thời gian bán",
    "l_nolimittime" => "Không giới hạn thời gian",
    "l_timeperiod" => "Thời gian hiệu lực",
    "l_channelsell" => "Kênh bán",
    "l_all" => "Tất cả",
    "l_settlement" => "Quyết toán",
    "l_settlement1" => "Quyết toán giá nộp tiền",
    "l_settlement2" => "Quyết toán giá bán",
    "l_conditionbuy" => "Điều kiện mua",
    "l_ammounttime" => "SL mua tối đa 1 lần",
    "l_ammountperson" => "SL mua tối đa 1 người",
    "l_0limit" => "* 0 là ko giới hạn",
    "l_addconditionbuy" => "Nhập thêm dk mua",
    "l_contentbuy" => "Nôi dung hướng dẫn mua",
    "l_usageNotice" => "Hướng dẫn",
    "l_smsNotice" => "Nội dung gởi SMS",
    "l_emailNotice" => "Nội dung gởi mail",
    "l_insuranceInfo" => "insuranceInfo",
    "l_listproduct1"=>"Mã deal kênh",
    "l_listproduct2"=>"Trạng thái bán",
    "l_listproduct3"=>"ngày bắt đầu bán",
    "l_listproduct4"=>"ngày ngưng bán",
    "l_listproduct5"=>"STT",
    "l_listproduct6"=>"QL",
    
    //
    "l_conditioncancel" => "Điều kiện hủy/Hoàn tiền",
    "l_cancelType" => "cancelType",
    "l_cancelPeriodType" => "cancelPeriodType",
    "l_cancelMarkType" => "cancelMarkType",
    "l_refund" => "refund",
    "l_refundOnBusinessDay" => "refundOnBusinessDay",
    "l_refundUnusedTicket" => "refundUnusedTicket",
    "l_notice" => "notice",
    "l_refundRates" => "refundRates",
    "l_tutorialcancel" => "Hướng dẫn hủy/hoàn tiền",
    "l_contentcancel" => "Nôi dung hủy/hoàn tiền",
    
    //
    "l_conditionused" => "Điều kiện sử dụng",
    "l_publication" => "publication",
    "l_externalCouponUseType" => "externalCouponUseType",
    "l_useBarcode" => "useBarcode",
    "l_isUseDirect" => "isUseDirect",
    "l_useExternalTicketNumber" => "useExternalTicketNumber",
    "l_ticketUsage" => "ticketUsage",
    "l_ticketSendCriteriaType" => "ticketSendCriteriaType",
    "l_ticketSendSpentTime" => "ticketSendSpentTime",
    "l_ticketSendLimitTime" => "ticketSendLimitTime",
    
    "l_businessinfo" => "Thông tin doanh nghiệp",
    "l_businessinfoaddress" => "Địa chỉ doanh nghiệp",
    "l_businessinfoedit" => "Sửa thông tin doanh nghiệp",
    "l_contacts" => "contacts",
    "l_introduction" => "introduction",
    "l_benefits" => "benefits",
    "l_inclusionNotice" => "inclusionNotice",
    "l_exclusionNotice" => "exclusionNotice",
    "l_additionalInfoPrompt" => "additionalInfoPrompt",
    
    //
    "l_ct_AUTO" => "Auto",
    "l_ct_APPROVAL" => "Approval",
    
    "l_ct_BEFORE_USE" => "BEFORE_USE",
    "l_ct_AFTER_7DAYS" => "AFTER_7DAYS",
    
    "l_ct_NONE" => "NONE",
    "l_ct_NOT_CANCELED" => "NOT_CANCELED",
    "l_ct_UNUSE_REFUND_ALL" => "UNUSE_REFUND_ALL",
    "l_ct_NOT_REFUND_AFTER_RECEIPT" => "NOT_REFUND_AFTER_RECEIPT",
    "l_ct_NOT_REFUND_AFTER_RESERVATION_CONFIRM" => "NOT_REFUND_AFTER_RESERVATION_CONFIRM",
    "l_ct_UNUSE_REFUND_ALL_BEFORE_ONE_DAY" => "UNUSE_REFUND_ALL_BEFORE_ONE_DAY",
    "l_ct_DEPENDING_ON_VENDOR" => "DEPENDING_ON_VENDOR",
    
    //
    "l_pub_PURCHASE" => "PURCHASE",
    "l_pub_BARCODE" => "BARCODE",
    "l_pub_BARCODE_REAL_TIME" => "BARCODE_REAL_TIME",
    "l_pub_E_TICKET" => "E_TICKET",
    "l_pub_DELIVERY" => "DELIVERY",
    "l_pub_ON_SITE" => "ON_SITE",
    
    "l_pub_DAY" => "DAY",
    "l_pub_TIME" => "TIME",
    "l_pub_NONE" => "NONE",
    
    //
    "l_close" => "Đóng",
    "l_addoption" => "Thêm option",
    "l_add" => "Thêm",
    "l_back" => "Trở lại",
    "l_save" => "Lưu",
	"l_postdone"=>"Đăng xong",
    "l_continue" => "Tiếp tục",
    "l_delete" => "Delete",
    "l_yes" => "YES",
    "l_no" => "NO",
    "l_confirm" => "Xác thực doanh nghiệp",
    "l_search" => "Tìm",
    "l_edit" => "Sửa",
    "l_reset" => "Reset",
    "l_anwser" => "Trả lời",
    "l_anwserbefore" => "Chờ trả lời",
    "l_anwserdone" => "Trả lời xong",
    "l_anwserpopup" => "답변등록 레이어",
    
    //
    "l_dateopensale" => "Ngày bán",
    "l_1week" => "1 tuần",
    "l_1month" => "1 tháng",
    "l_3month" => "3 tháng",
    "l_keyword" => "Từ khóa",

    "l_status10" => "Tất cả",
    "l_status0" => "Lưu tạm",
    "l_status1" => "Chờ duyệt",
    "l_status2" => "Chờ bán",
    "l_status3" => "Đang bán",
    "l_status4" => "Bán xong",
    "l_status_1" => "Ngưng bán",
    "l_status_6" => "Duyệt xong",
    
    //
    "l_addticket1"=>"searchTags lớn hơn 10",
    "l_addticket2"=>"Hãy nhập đầy đủ option",
    "l_addticket3"=>"Option sản phẩm",
    "l_addticket4"=>"Đăng sp voucher",
    "l_addticket5"=>"Đăng sp ngày",
    "l_addticket6"=>"Sau khi nhập giá trị option, nhấn nút [Thêm vào danh sách option] thì option sẽ tự động được tổ hợp và thêm vào danh sách option.",
    "l_addticket7"=>"Đối với loại option như người lớn/trẻ em phải setting theo tiêu chuẩn người sử dụng, thì đăng giá trị option ở trường option chi tiết theo tiêu chuẩn người sử dụng.",
    "l_addticket8"=>"Sau khi đăng option thì thiết lập giá/số lượng bán của từng option trong danh sách option",
    "l_addticket9"=>"Option chi tiết",
    "l_addticket10"=>"Tiêu chuẩn người sử dụng",
    "l_addticket11"=>"Thêm vào option",
    "l_addticket12"=>"Quy định ngày",
    "l_addticket13"=>"Giá cơ bản",
    "l_addticket14"=>"Giá cuối tuần",
    "l_addticket16"=>"Xem option đã thêm bằng cách nhập trực tiếp hoặc bằng file excel, có thể sửa giá thường/giá bán/số lượng bán/thời gian bán của từng option.",
    "l_addticket17"=>'Sau khi đăng sản phẩm, có thể xem số lượng bán và thời gian bán của từng kênh ở menu quản lý "Phí/Số lượng".',
    "l_addticket18"=>"Giá đại diện",
    "l_addticket19"=>"Giá thường",
    "l_addticket20"=>"Giá bán",
    "l_addticket21"=>"Số lượng",
    "l_addticket22"=>"Ngày bắt đầu hiệu lực",
    "l_addticket23"=>"Ngày kết thúc hiệu lực",
    "l_addticket24"=>"Mã Option theo kênh",
    "l_addticket25"=>"Tự động so khớp",
    "l_addticket26"=>"Nhập tên option",
    "l_addticket27"=>"Nhập tên option chi tiết",
    "l_typebusinees1"=>"Loại hình DN/ Ngành nghề",
    "l_typebusinees2"=>"Loại hình doanh nghiệp",
    //dashboard
    "l_dashboard"=>"Dashboard",
    "l_product"=>"Sản phẩm",
    "l_question"=>"Câu hỏi",
    "l_dashboard1"=>"Số sản phẩm thời gian thực",
    "l_dashboard2"=>"Số sản phẩm sắp kết thúc",
    "l_dashboard3"=>"Số sản phẩm sắp mở",
    "l_dashboard4"=>"Số lượng mua hôm nay",
    "l_dashboard5"=>"Số lượng vé chưa sử dụng",
    "l_dashboard6"=>"Số sản phẩm không bán được",
    "l_dashboard7"=>"Số câu hỏi chưa trả lời",
    "l_dashboard8"=>"Biểu đồ số lượng mua theo tuần",
    "l_dashboard9"=>"Biểu đồ số lượng sử dụng theo tuần",
    
    "l_imagerepresentative" => "Hình đại điện",
    
    // Quản lý sản phẩm
    "l_listproduct7"=>"Vui lòng chọn ít nhất 1 sản phẩm",
    "l_listproduct8"=>"Chỉ áp dụng cho sản phẩm chờ duyệt",
    "l_listproduct9"=>"Chỉ áp dụng cho sản phẩm chờ duyệt, sản phẩm chờ bán, sản phẩm đang bán.",
    "l_listproduct10"=>"Chỉ áp dụng cho sản phẩm ngưng bán.",
    "l_listproduct11"=>"Đây là danh sách sản phẩm được thu thập lúc ",
    "l_listproduct12"=>"Update mỗi 5 phút",
    "l_update"=>"Update",
    "l_listproduct13"=>"Chỉ xem sản phẩm mãi mãi",
    "l_listproduct14"=>"Duyệt bán",
    "l_listproduct15"=>"Ngưng bán",
    "l_listproduct16"=>"Mở lại",
    "l_listproduct17"=>"Sửa thời gian bán",
    "l_listproduct18"=>"Thay đổi ngày ngưng bán",
    "l_listproduct19"=>"Vui lòng thiết lập ngày ngưng bán.",
    "l_listproduct20"=>"Ngày ngưng bán",
    
    // Quản lý hỏi đáp
    "l_question1"=>"Quản lý hỏi đáp",
    "l_question2"=>"Đây là danh sách câu hỏi được thu thập lúc 9:00 ngày 21/12. (Update mỗi 5 phút)",
    "l_question3"=>"Ngày hỏi",
    "l_question4"=>"Xem tất cả",
    "l_question5"=>"Nội dung câu hỏi",
    "l_question6"=>"Tên người hỏi",
    "l_question7"=>"Mã câu hỏi",
    "l_question8"=>"Đặt hàng",
    "l_question9"=>"Ngày trả lời",
    
    // Quản lý đơn hàng
    "l_confirmuse"=>"Sử dụng",
    "l_confirmrestore"=>"Khôi phục",
    "l_rowemptydata"=>"Dữ liệu rỗng!",
    "l_orderdone"=>"Mua xong",
    "l_orderusedone"=>"Sử dụng xong",
    "l_orderreturningprice"=>"Đang yêu cầu hoàn tiền",
    "l_orderreturnprice"=>"Hoàn tiền xong",
    "l_orderdie"=>"Hết hiệu lực",
    "l_orderwarning1"=>"Vui lòng chọn sản phẩm có trạng thái là Mua xong",
    "l_orderwarning2"=>"Vui lòng chọn sản phẩm có trạng thái là Sử dụng xong",
    "l_orderwarning3"=>"Sản phẩm bạn chọn sẽ được xử lý sử dụng. Bạn có muốn tiếp tục không?",
    "l_orderwarning4"=>"Sản phẩm bạn chọn sẽ được xử lý khôi phục. Bạn có muốn tiếp tục không?",
    "l_order1"=>"Ngày mua",
    "l_order2"=>"Khôi phục vé",
    "l_order3"=>"Chỉ xem vé đã khôi phục",
    "l_order4"=>"Trạng thái vé",
    "l_order5"=>"Tên người mua",
    "l_order6"=>"Mã đh của kênh",
    "l_order7"=>"Mã deal của kênh",
    "l_order8"=>"Mã option của kênh",
    "l_order9"=>"Mã vé T-Bridge",
    "l_order10"=>"Mã vé kênh bán",
    "l_order11"=>"Mã sp/Mã deal",
    "l_order12"=>"Mã option/Mã option(kênh)",
    "l_order13"=>"Giá mua",
    
    //Chi tiết doanh thu
    "l_chooseproduct"=>"Chọn sản phẩm",
    "l_quantitysoldorder"=>"Số lượng đặt",
    "l_amountsoldorder"=>"Số tiền đặt",
    "l_quantitysoldcancel"=>"Số lượng hủy",
    "l_amountsoldcancel"=>"Số tiền hủy",
    "l_quantitysoldreal"=>"Sl bán thực",
    "l_amountsoldreal"=>"Số tiền bán thực tế",
    "l_quantitysolduse"=>"SL xử lý sử dụng",
    "l_amountsolduse"=>"Số tiền xử lý sử dụng",
    "l_timefind"=>"Thời gian tìm kiếm",
    "l_synthetic"=>"Tổng hợp",
    "l_revenue1"=>"Chi tiết số lượng bán thực tế",
    "l_revenue2"=>"Chi tiết doanh thu từng option của sản phẩm",
    "l_today"=>"Hôm nay",
    
    // Quyết toán
    "l_revenuemonth"=>"QT tháng",
    "l_revenuelog"=>"Lần",
    "l_revenue01"=>"Ngày quyết toán dự kiến",
    "l_revenue02"=>"Loại QT",
    "l_revenue03"=>"Lần QT",
    "l_revenue04"=>"Tỷ lệ QT",
    "l_revenue05"=>"Thời gian QT",
    "l_revenue06"=>"Ngày dự kiến QT",
    "l_revenue07"=>"Phí của kênh",
    "l_revenue08"=>"Giá bao gồm phí", 
    "l_revenue09"=>"Xem bảng QT",
    "l_revenue10"=>"Chờ GĐ duyệt",
    "l_revenue11"=>"GĐ duyệt xong",
    "l_revenue12"=>"GĐ từ chối duyệt",
    "l_revenue13"=>"Sửa bảng QT",
    "l_revenue14"=>"Thời gian",
    "l_revenue15"=>"Ngày đăng bảng QT",
    "l_revenue16"=>"Ngày thanh toán dự kiến",
    "l_revenue17"=>"Trạng thái QT",
    "l_revenue18"=>"Từ chối",
    "l_revenue19"=>"QT xong",
    "l_revenue20"=>"Phí",
    "l_revenue21"=>"Số tiền QT",
    "l_revenue22"=>"Ngày cập nhật cuối cùng bảng QT",
    "l_revenue23"=>"Người cập nhật cuối cùng bảng QT",
    "l_revenue24"=>"Quyết toán xong",
    "l_revenue25"=>"Vui lòng chọn bảng QT có trạng thái là chờ GĐ duyệt",
    "l_revenue26"=>"Vui lòng chọn bảng QT có trạng thái là GĐ duyệt xong",
    "l_revenue27"=>" bảng quyết toán đã bị từ chối.",
    "l_revenue28"=>" bảng quyết toán thay đổi trạng thái thành QT xong",
    "l_revenue29"=>" bảng quyết toán thay đổi trạng thái thành xét duyệt xong",
    "l_revenue30"=>" bảng quyết toán thay đổi trạng thái thành chờ GĐ duyệt",
    //Chi tiết quyết toán
    "l_statusmew0"=>"Cũ",
    "l_statusmew1"=>"Mới",
	"l_alertticket"=>"Sản phẩm chưa được khởi tạo",
    "l_hashtageditticket2" => "# Tỷ lệ phí của mỗi kênh khác nhau tùy theo phân loại sản phẩm, có thể sửa được",
    "l_guiderecipe" => "Số lượng bán thực tế = Số lượng đăt hàng - Số lượng hủy.",
	"l_charjsweek1"=>"Tuần này",
	"l_charjsweek2"=>"Tuần trước",
    
    // Tương tự số điện thoại bàn
    "l_asaphonetable" => "Giống điện thoại bàn",
    
	//tam
    "l_dieukhoan"=>"Điều khoản chính sách",
    "l_chinhsach"=>"Chính sách sử dụng thông tin cá nhân",
    "l_orderall"=>"Xem toàn bộ đơn hàng",
    "l_homqua"=>"Hôm qua",
    "l_homnay"=>"Hôm nay",
    "l_soveban"=>"Số vé bán",
    "l_sovesudung"=>"Số vé sử dụng",
    "l_tinhhinhbanve"=>"Tình hình bán vé",
    "l_xemthongbao"=>"Xem thông báo",
    "l_toanbo"=>"Toàn bộ",
    "l_textsearch"=>"Tìm tên/số điện thoại/mã vé",
    "l_dieukien"=>"Điều kiện chi tiết",
    "l_7ngay"=>"7 ngày gần nhất",
    "l_1thang"=>"1 tháng gần nhất",
    "l_3thang"=>"3 tháng gần nhất",
    "l_6thang"=>"6 tháng gần nhất",
    "l_tructiep"=>"Nhập trực tiếp",
    "l_tructiepthoigian"=>"Nhập trực tiếp thời gian",
    "l_kenhsearch"=>"Kênh (có thể chọn nhiều kênh)",
    "l_apdung"=>"Áp dụng",
    "l_boloc"=>"Bộ lọc",
    "l_checkall"=>"Chọn tất cả",
    "l_finid_mobi"=>"Để tìm ID/PW, vui lòng sử dụng PC version",
    "l_pcversion"=>"PC version",
    "l_orderrefundmoney"=>'Đang yêu cầu hoàn tiền'
];
?>